import Head from "next/head";
import { Canvas, useFrame } from "@react-three/fiber";
import { Model } from "@/Components/Scene";
import * as THREE from "three";
import { OrbitControls } from "@react-three/drei";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="app">
        <Canvas>
          <ambientLight intensity={0.6} />
          <Model scale={0.007} position={[0, -1.16, 0]} />

          {/* <OrbitControls /> */}
        </Canvas>
      </main>
    </>
  );
}
