/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 SillyDance.glb
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function SillyDance(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/SillyDance.glb");
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    console.log(actions);
    actions["Armature|mixamo.com|Layer0"].play();
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <group name="parasiteZombie">
            <skinnedMesh
              name="parasiteZombie001"
              geometry={nodes.parasiteZombie001.geometry}
              material={materials["parasitezombie_Material1.001"]}
              skeleton={nodes.parasiteZombie001.skeleton}
            />
            <skinnedMesh
              name="parasiteZombie001_1"
              geometry={nodes.parasiteZombie001_1.geometry}
              material={materials["parasitezombie_Material.001"]}
              skeleton={nodes.parasiteZombie001_1.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/SillyDance.glb");
